# Build phenix source tarball

# no continuous integration builds or pull requests
trigger: none
pr: none

schedules:
  - cron: '0 3 * * *'
    displayName: Nightly source update
    branches:
      include:
      - main
    always: true

# template location
resources:
  repositories:
    - repository: cctbx_project
      type: github
      name: cctbx/cctbx_project
      endpoint: phenix-installer
  pipelines:
  - pipeline: data_cache
    source: 'Update data cache'

jobs:
- job: Build_phenix_source_tarball
  pool:
    vmImage: ubuntu-latest
  timeoutInMinutes: 360

  # variables for version
  variables:
  - name: year
    value: $(Get-Date -Format yyyy)
  - name: month
    value: $(Get-Date -Format MM)
  - name: day
    value: $(Get-Date -Format dd)
  - name: version
    value: $(year).$(month).a$(day)
  # variable for Google Drive folder
  - name: folder_id
    value: 1m2p6k6UdF798vlH1D6eemvTqngj5Ei-q
  # variable for secrets
  - group: ENV_GROUP

  steps:

  - task: DownloadSecureFile@1
    name: upload_key
    inputs:
      secureFile: phenix-lbl-04e6cb0d1bf7.json

  - task: DownloadSecureFile@1
    name: ssh_config
    inputs:
      secureFile: ssh.config

  # ubuntu setup
  - script: |
      sudo apt-get install -y build-essential curl git libgl1-mesa-dev libglu1-mesa-dev locales subversion
      sudo locale-gen en_US.UTF-8
      sudo update-locale
    displayName: Install dependencies for Ubuntu

  # set version
  - powershell: |
      $trimmed_month = $(month).TrimStart("0")
      $trimmed_day = $(day).TrimStart("0")
      Write-Host $trimmed_month
      Write-Host $trimmed_day
      Write-Host "##vso[task.setVariable variable=year]$(year)"
      Write-Host "##vso[task.setVariable variable=month]$trimmed_month"
      Write-Host "##vso[task.setVariable variable=day]$trimmed_day"
      Write-Host $(year)
      Write-Host $(month)
      Write-Host $(day)
    displayName: Set variables from date

  - script: |
      # version=$(year).$(month).a$(day)
      version=`python3 -c 'import time; print("dev-%s"%(int((time.time() - 1255046400) / (24*60*60))))'`
      echo "##vso[task.setVariable variable=version]$version"
      echo $(version)
    displayName: Set version

  - script: |
      set -xe
      # release=`echo $(Build.SourceBranch) | sed 's/refs\/heads\/releases\///'`
      release=`python3 -c 'import time; print("1.21rc1-%s"%(int((time.time() - 1255046400) / (24*60*60))))'`
      echo "##vso[task.setVariable variable=version]$release"
      echo $(version)
    displayName: Override version for release branch
    condition: startswith(variables['Build.SourceBranch'], 'refs/heads/releases/')

  # add conda to path
  # https://docs.microsoft.com/en-us/azure/devops/pipelines/ecosystems/anaconda?view=azure-devops&tabs=ubuntu-16-04#add-conda-to-your-system-path
  - bash: echo "##vso[task.prependpath]$CONDA/bin"
    displayName: Add conda to PATH

  # download support scripts
  - checkout: self
    path: ./phenix-installer

  # link bootstrap.py
  - script: |
      set -xe
      cd $(Pipeline.Workspace)
      wget https://raw.githubusercontent.com/cctbx/cctbx_project/master/libtbx/auto_build/bootstrap.py
      mkdir modules
    displayName: Download bootstrap.py

  # download test data
  - template: .azure-pipelines/templates/download-data-cache.yml@cctbx_project

  # download remaining sources
  - script: |
      set -xe
      export SVN_SSH="ssh -F $(ssh_config.secureFilePath)"
      cd $(Pipeline.Workspace)
      python bootstrap.py hot update \
        --builder=phenix_release \
        --use-conda \
        --python 37 \
        --cciuser=builder
    displayName: Download remaining sources

  - script: |
      set -xe

      git config user.name "Do Not Merge"
      git config user.email "do_not@mer.ge"

      cd $(Pipeline.Workspace)/modules/cctbx_project
      git revert --no-edit 27582271c88757549cf9e320ca1b754c20de15b5
    displayName: Revert std::shared_ptr for DIALS 3.8

  # base and build
  - script: |
      set -xe
      cd $(Pipeline.Workspace)
      export CCTBX_SKIP_CHEMDATA_CACHE_REBUILD=1
      python bootstrap.py base build \
        --builder=phenix_release \
        --use-conda \
        --python 37 \
        --nproc=4
    displayName: Configure and Build

  # remove symoblic link for Windows
  - script: |
      set -xe
      cd $(Pipeline.Workspace)/modules/phenix/wxGUI2/images
      rm -f splash-refine.png
      cp splash-refine-1.3.png splash-refine.png
    displayName: Remove symoblic link to image

  # build source tarball
  # build/bin/libtbx.create_installer --version $(version) --install_script modules/cctbx_project/libtbx/auto_build/plus_installer.py --dist_dir dist/$(version) tmp/cctbx-$(version)
  - script: |
      set -xe
      cd $(Pipeline.Workspace)
      build/bin/libtbx.create_installer \
        --version $(version) \
        --install_script modules/phenix/phenix/installer/phenix_voyager_installer.py \
        --license modules/phenix/LICENSE.txt --readme modules/phenix/CHANGES \
        --readme modules/phenix/phenix/installer/README \
        --readme modules/phenix/phenix/installer/SOURCES \
        --dist_dir dist/$(version) \
        tmp/phenix-installer-$(version)-source
      rm -fr build tmp modules
      cd ./dist/$(version)
      tar -xf phenix-installer-$(version)-source.tar.gz
      export XZ_OPT=-9
      tar -Jcf phenix-installer-$(version)-source.tar.xz phenix-installer-$(version)-source
      openssl enc \
        -aes-256-cbc \
        -salt \
        -md sha256 \
        -iter 100000 \
        -pbkdf2 \
        -in phenix-installer-$(version)-source.tar.xz \
        -out phenix.enc \
        -pass env:TARBALL_PASSWORD
    displayName: Build source tarball

  # create folders for conda packages and installers
  - script: |
      set -xe

      conda create -n upload -y -c conda-forge python=3.9 pydrive2 boost=1.74 tabulate tqdm
      source activate upload
      conda install -y -c xfel -c conda-forge --no-deps cctbx.xfel

      for d in 3.7 3.8 3.9 3.10 linux-64 osx-64 osx-arm64 win64; do
        libtbx.python $(Pipeline.Workspace)/phenix-installer/scripts/upload_installer.py \
          --credentials $(upload_key.secureFilePath) \
          --folder_id $(folder_id) \
          --folder_list "$(version)/${d}"
        sleep 10
      done
    displayName: Create folders for conda packages and installers
    continueOnError: true

  # publish complete source tarball as artifact
  - publish: $(Pipeline.Workspace)/dist/$(version)/phenix.enc
    artifact: phenix
    continueOnError: true

  # upload full source tarball to Google Drive
  - script: |
      set -xe

      source activate upload

      libtbx.python $(Pipeline.Workspace)/phenix-installer/scripts/upload_installer.py \
        --credentials $(upload_key.secureFilePath) \
        --folder_id $(folder_id) \
        --folder_list $(version) \
        --files $(Pipeline.Workspace)/dist/$(version)/phenix-installer-$(version)-source.tar.xz
    displayName: Upload full source tarball (xz) to Google Drive
    continueOnError: true
